version: '3.5'

services:
  node_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  python_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
